CREATE TABLE IF NOT EXISTS author
(
    author_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    birth_date DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS album
(
    album_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_name   VARCHAR(255) NOT NULL,
    created_date DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS song
(
    song_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_name VARCHAR(255) NOT NULL,
    duration  REAL         NOT NULL,
    album_id  BIGINT       NOT NULL REFERENCES album (album_id)
);

CREATE TABLE IF NOT EXISTS author_songs
(
    author_id BIGINT NOT NULL,
    song_id   BIGINT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES author (author_id),
    FOREIGN KEY (song_id) REFERENCES song (song_id)
);
