CREATE TABLE IF NOT EXISTS author
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    birth_date DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS album
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_name   VARCHAR(255) NOT NULL,
    created_date DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS song
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_name VARCHAR(255) NOT NULL,
    duration  REAL         NOT NULL,
    album_id  BIGINT       NOT NULL REFERENCES album (id)
);

CREATE TABLE IF NOT EXISTS author_songs
(
    authors_id BIGINT NOT NULL,
    songs_id   BIGINT NOT NULL,
    FOREIGN KEY (authors_id) REFERENCES author (id),
    FOREIGN KEY (songs_id) REFERENCES song (id)
);
